spring.application.name=jutjubic
spring.datasource.driverClassName=org.postgresql.Driver
spring.sql.init.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/jutjubic
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=true
jwt.secret=a-valid-string-secret-that-is-at-least-512-bits-long-which-is-very-long
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=205MB
spring.jpa.database-platform=org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect

management.endpoints.web.exposure.include=health,info,prometheus
management.prometheus.metrics.export.enabled=true
management.endpoint.metrics.enabled=true

# Spring Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mejl.za.projekte.kojov@gmail.com
spring.mail.password=dmfpjwichxtjhwgu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# rabbitmq
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

video.upload-dir=uploads/videos/upload
video.processed-dir=uploads/videos/processed
video.thumbnail-dir=uploads/thumbnails

#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=user
#spring.rabbitmq.password=password

logging.level.org.springframework.amqp=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.rabbitmq=DEBUG

ffmpeg.path=ffmpeg

